spring:
  application:
    name: service-customer

server:
  port: 8084

management:
  server:
    port: 8084
  endpoints:
    web:
      exposure:
        include: "*"

#开启 Hystrix
feign:
  hystrix:
    enabled: true


logging:
  level:
    root: "info"